import Head from "next/head";
import NavBar from "@/components/navbar";
import { client } from "@/lib/sanity.client";
import { queryNav } from "@/query/quieries";
import { INavData } from "@/interfaces/INav";

interface IHome {
  data: INavData[];
}

export default function Home({ data }: IHome) {
  return (
    <>
      <Head>
        <title>Anthony Stolp Sanity Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <span>
          <NavBar data={data} />
        </span>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const fetchedData = await client.fetch(queryNav);
  {
    console.log(fetchedData, "fetcheddatatatataa");
  }

  return { props: { data: fetchedData } };
};
