import Head from "next/head";
import { IStrain } from "@/interfaces/IStrain";
import { fetchedStrains } from "@/static-props/fetched-strains";
import { fetchedNavigation } from "@/static-props/fetched-navigation";
import NavBar from "@/components/navbar";
import { INav } from "@/interfaces/INav";
interface HomeProps {
  fetchedNavData: INav[];
  fetchedStrainData: IStrain[];
}

export default function Home(props: HomeProps) {
  const { fetchedNavData, fetchedStrainData } = props;

  return (
    <>
      <Head>
        <title>Anthony Stolp Sanity Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <NavBar fetchedData={fetchedNavData} />
      </main>
    </>
  );
}
export async function getStaticProps() {
  const fetchedStrainData = await fetchedStrains();

  const fetchedNavData = await fetchedNavigation();
  return { props: { fetchedNavData, fetchedStrainData } };
}
